// <auto-generated />
using System;
using FSH.Modules.Expendable.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSH.Playground.Migrations.PostgreSQL.Expendable
{
    [DbContext(typeof(ExpendableDbContext))]
    [Migration("20260329120000_AddProductVariants")]
    partial class AddProductVariants
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal: the model snapshot is authoritative; migration only adds columns & FK
        }
    }
}
